# Generated by Django 4.2.4 on 2023-09-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_vendor",
            field=models.BooleanField(default=False),
        ),
    ]
