# Generated by Django 4.2.4 on 2023-09-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_product_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/product_images/thumbnails/"
            ),
        ),
    ]
